### ISSUE TITLE
checksum mismatch when trying to install plugin

### ISSUE THREAD

**Issue by daniellwu** [jenkinsci/lockable-resources-plugin#67]
Trying to install version 2.0 plugin from Jenkins 2.64, and getting this error

```
java.io.IOException: Downloaded file /var/lib/jenkins/plugins/lockable-resources.jpi.tmp does not match expected SHA-1, expected 'tuLn+UmElP/9wLnBhRme0QZAues=', actual 'f9lfA56w1mbVlpFYsOkHsb3HRDs='
	at hudson.model.UpdateCenter.verifyChecksums(UpdateCenter.java:1810)
	at hudson.model.UpdateCenter.access$1100(UpdateCenter.java:149)
	at hudson.model.UpdateCenter$InstallationJob.replace(UpdateCenter.java:1963)
	at hudson.model.UpdateCenter$UpdateCenterConfiguration.install(UpdateCenter.java:1194)
	at hudson.model.UpdateCenter$DownloadJob._run(UpdateCenter.java:1680)
	at hudson.model.UpdateCenter$InstallationJob._run(UpdateCenter.java:1874)
	at hudson.model.UpdateCenter$DownloadJob.run(UpdateCenter.java:1651)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at hudson.remoting.AtmostOneThreadExecutor$Worker.run(AtmostOneThreadExecutor.java:110)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by TobiX** [comment]
Not relevant anymore, since 2.0 isn't the newest release anymore.
