### ISSUE TITLE
Lockable resources plugin fails to load because of a dependency on DataTables.net API Plugin version

### ISSUE THREAD

**Issue by sunkuamzn** [jenkinsci/lockable-resources-plugin#700]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
Upgrading Jenkins v2.462.1 to v2.462.2
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Ubuntu 22

### Reproduction steps

Jenkins trying to load the lockable resources plugin

### Expected Results

Jenkins able to load the plugin

### Actual Results

```
2024-09-09 15:31:00.195+0000 [id=43] INFO jenkins.InitReactorRunner$1#onAttained: Started initialization
2024-09-09 15:31:00.203+0000 [id=42] INFO hudson.PluginManager#loadDetachedPlugins: Upgrading Jenkins. The last running version was 2.462.1. This Jenkins is version 2.462.2.
2024-09-09 15:31:00.332+0000 [id=42] INFO hudson.PluginManager#loadDetachedPlugins: Upgraded Jenkins from version 2.462.1 to version 2.462.2. Loaded detached plugins (and dependencies): []
2024-09-09 15:31:05.851+0000 [id=71] INFO jenkins.InitReactorRunner$1#onAttained: Listed all plugins
2024-09-09 15:31:06.839+0000 [id=48] SEVERE jenkins.InitReactorRunner$1#onTaskFailed: Failed Loading plugin Lockable Resources plugin v1301.v0e3b_da_4b_4462 (lockable-resources)
java.io.IOException: Failed to load: Lockable Resources plugin (lockable-resources 1301.v0e3b_da_4b_4462)
- Update required: DataTables.net API Plugin (data-tables-api 2.0.8-1) to be updated to 2.1.4-1 or higher
at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:992)
at hudson.PluginManager$2$1$1.run(PluginManager.java:555)
at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:177)
at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.ja
at jenkins.model.Jenkins$5.runTask(Jenkins.java:1175)
at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:221)
at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:120)
at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
```

**Comment by sunkuamzn** [comment]
Manually updating DataTables.net API Plugin fixed the problem
