### ISSUE TITLE
java.lang.NullPointerException: Cannot enter synchronized block because "this.logs" is null

### ISSUE THREAD

**Issue by marvinthepa** [jenkinsci/lockable-resources-plugin#731]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
    Jenkins 2.479.1
    openjdk version "21.0.2" 2024-01-16 (build node)
    openjdk version "17.0.13" 2024-10-15 (controller node)
    Lockable Resources plugin Version 1327.ved786b_a_197e0
  ```
  
  I would prefer not to make my whole environment public. Let me know if you need specific versions of specific other plugins.
</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

controller: Ubuntu 20.04.6
build node: OpenBSD 7.5

### Reproduction steps

Build two jobs that have the following in their Jenkinsfile:

```groovy
pipeline {
    options {
        ....
        lock resource: 'foo'
    }
```

### Expected Results

No stacktrace, successful build.

### Actual Results

```
java.lang.NullPointerException: Cannot enter synchronized block because "this.logs" is null
	at PluginClassLoader for lockable-resources//org.jenkins.plugins.lockableresources.actions.LockedResourcesBuildAction.addLog(LockedResourcesBuildAction.java:97)
	at PluginClassLoader for lockable-resources//org.jenkins.plugins.lockableresources.actions.LockedResourcesBuildAction.addLog(LockedResourcesBuildAction.java:92)
	at PluginClassLoader for lockable-resources//org.jenkins.plugins.lockableresources.actions.LockedResourcesBuildAction.addLog(LockedResourcesBuildAction.java:84)
	at PluginClassLoader for lockable-resources//org.jenkins.plugins.lockableresources.LockStepExecution$Callback.finished(LockStepExecution.java:234)
	at PluginClassLoader for workflow-step-api//org.jenkinsci.plugins.workflow.steps.BodyExecutionCallback$TailCall.onSuccess(BodyExecutionCallback.java:119)
	at PluginClassLoader for workflow-cps//org.jenkinsci.plugins.workflow.cps.CpsBodyExecution$SuccessAdapter.receive(CpsBodyExecution.java:381)
	at PluginClassLoader for workflow-cps//com.cloudbees.groovy.cps.Block$Noop.eval(Block.java:30)
	at PluginClassLoader for workflow-cps//com.cloudbees.groovy.cps.Next.step(Next.java:83)
	at PluginClassLoader for workflow-cps//com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:147)
	at PluginClassLoader for workflow-cps//org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:17)
	at PluginClassLoader for workflow-cps//org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:49)
	at PluginClassLoader for workflow-cps//org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:180)
	at PluginClassLoader for workflow-cps//org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:422)
	at PluginClassLoader for workflow-cps//org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:330)
	at PluginClassLoader for workflow-cps//org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:294)
	at PluginClassLoader for workflow-cps//org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService.lambda$wrap$4(CpsVmExecutorService.java:140)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:139)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
	at jenkins.util.ErrorLoggingExecutorService.lambda$wrap$0(ErrorLoggingExecutorService.java:51)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at PluginClassLoader for workflow-cps//org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$1.call(CpsVmExecutorService.java:53)
	at PluginClassLoader for workflow-cps//org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$1.call(CpsVmExecutorService.java:50)
	at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:136)
	at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:275)
	at PluginClassLoader for workflow-cps//org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService.lambda$categoryThreadFactory$0(CpsVmExecutorService.java:50)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

What is even worse, the lock that is held by this build is not released, so no other can execute.

### Are you interested in contributing a fix?

I would like to, but it would probably take some time as I have no setup to develop / test Jenkins Plugins and have no idea how `logs` could be `null` here in the first place.

**Comment by marvinthepa** [comment]
I just realized that this happened during the Jenkins Upgrade, not after.
So I guess this is not really an issue.
