### ISSUE TITLE
[JENKINS-64127] ConcurrentModificationException from lock step

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkinsci/lockable-resources-plugin#933]
<p> </p>

<pre>
 java.util.ConcurrentModificationException
  at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
  at java.util.ArrayList$Itr.next(ArrayList.java:859)
  at org.jenkins.plugins.lockableresources.LockableResourcesManager.getAllLabels(LockableResourcesManager.java:136)
  at org.jenkins.plugins.lockableresources.LockableResourcesManager.isValidLabel(LockableResourcesManager.java:131)
  at org.jenkins.plugins.lockableresources.LockStepResource.validate(LockStepResource.java:87)
  at org.jenkins.plugins.lockableresources.LockStep.validate(LockStep.java:138)
  at org.jenkins.plugins.lockableresources.LockStepExecution.start(LockStepExecution.java:38)
  at org.jenkinsci.plugins.workflow.cps.DSL.invokeStep(DSL.java:286)
  at org.jenkinsci.plugins.workflow.cps.DSL.invokeMethod(DSL.java:179)
  at org.jenkinsci.plugins.workflow.cps.CpsScript.invokeMethod(CpsScript.java:122)
  at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:48)
  at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
  at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
  at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.methodCall(DefaultInvoker.java:20)
</pre>
<p> </p>

<p>Based on the code, this can also happen for the following methods:</p>

<p> </p>

<pre>
org.jenkins.plugins.lockableresources.LockableResourcesManager#checkCurrentResourcesStatus
org.jenkins.plugins.lockableresources.LockableResourcesManager#fromName
org.jenkins.plugins.lockableresources.LockableResourcesManager#getAllLabels
org.jenkins.plugins.lockableresources.LockableResourcesManager#getDeclaredResources
org.jenkins.plugins.lockableresources.LockableResourcesManager#getFreeResourceAmount
org.jenkins.plugins.lockableresources.LockableResourcesManager#getResourcesFromBuild
org.jenkins.plugins.lockableresources.LockableResourcesManager#getResourcesFromProject
org.jenkins.plugins.lockableresources.LockableResourcesManager#getResourcesWithLabel
org.jenkins.plugins.lockableresources.LockableResourcesManager#getResourcesMatchingScript
</pre>
<p> </p>

---
<details><summary><i>Originally reported by <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=seyguai">seyguai</a>, imported from: <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-64127" target="_blank">ConcurrentModificationException from lock step</a></i></summary>
<i><ul>
<li><b>status</b>: Open
<li><b>priority</b>: Major
<li><b>component(s)</b>: lockable-resources-plugin
<li><b>resolution</b>: Unresolved
<li><b>votes</b>: 0
<li><b>watchers</b>: 1
<li><b>imported</b>: 20251217-081411
</ul></i>
<details><summary>Raw content of original issue</summary>

<pre>
<p> </p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java"> java.util.ConcurrentModificationException
  at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
  at java.util.ArrayList$Itr.next(ArrayList.java:859)
  at org.jenkins.plugins.lockableresources.LockableResourcesManager.getAllLabels(LockableResourcesManager.java:136)
  at org.jenkins.plugins.lockableresources.LockableResourcesManager.isValidLabel(LockableResourcesManager.java:131)
  at org.jenkins.plugins.lockableresources.LockStepResource.validate(LockStepResource.java:87)
  at org.jenkins.plugins.lockableresources.LockStep.validate(LockStep.java:138)
  at org.jenkins.plugins.lockableresources.LockStepExecution.start(LockStepExecution.java:38)
  at org.jenkinsci.plugins.workflow.cps.DSL.invokeStep(DSL.java:286)
  at org.jenkinsci.plugins.workflow.cps.DSL.invokeMethod(DSL.java:179)
  at org.jenkinsci.plugins.workflow.cps.CpsScript.invokeMethod(CpsScript.java:122)
  at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:48)
  at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
  at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
  at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.methodCall(DefaultInvoker.java:20)
</pre>
</div></div>
<p> </p>

<p>Based on the code, this can also happen for the following methods:</p>

<p> </p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">org.jenkins.plugins.lockableresources.LockableResourcesManager#checkCurrentResourcesStatus
org.jenkins.plugins.lockableresources.LockableResourcesManager#fromName
org.jenkins.plugins.lockableresources.LockableResourcesManager#getAllLabels
org.jenkins.plugins.lockableresources.LockableResourcesManager#getDeclaredResources
org.jenkins.plugins.lockableresources.LockableResourcesManager#getFreeResourceAmount
org.jenkins.plugins.lockableresources.LockableResourcesManager#getResourcesFromBuild
org.jenkins.plugins.lockableresources.LockableResourcesManager#getResourcesFromProject
org.jenkins.plugins.lockableresources.LockableResourcesManager#getResourcesWithLabel
org.jenkins.plugins.lockableresources.LockableResourcesManager#getResourcesMatchingScript
</pre>
</div></div>
<p> </p></pre>
</details>
</details>
<details><summary><i>environment</i></summary>

```
Lockable Resources Plugin 2.10<br/>
Jenkins 2.235.3
```
</details>

**Comment by mPokornyETM** [comment]
## Fix submitted: PR #1020

The original report listed 10 methods vulnerable to `ConcurrentModificationException`. After reviewing the current codebase:

| Method | Status |
|--------|--------|
| `getAllLabels()` | Already fixed (uses `getReadOnlyResources()`) |
| `isValidLabel()` | Already fixed (`synchronized(syncResources)`) |
| `fromName()` | Already fixed (`synchronized(syncResources)`) |
| `getResourcesWithLabel()` | Already fixed (`synchronized(syncResources)`) |
| `getResourcesMatchingScript()` | Already fixed (`synchronized(syncResources)`) |
| `getFreeResourceAmount()` | Already fixed (calls synchronized method) |
| `getResourcesFromBuild()` | Removed entirely |
| `checkCurrentResourcesStatus()` | Safe — private, only called from within `synchronized(syncResources)` in `tryQueue()` |
| **`getDeclaredResources()`** | **Fixed in PR #1020** |
| **`getResourcesFromProject()`** | **Fixed in PR #1020** |

PR #1020 adds `synchronized(syncResources)` to the last two unprotected methods.
